class APIPaths:
    HEALTH             = "/api/health"
    MEETINGS           = "/api/meetings"
    MEETING_DETAIL     = "/api/meetings/{id}"
    MEETING_UPLOAD     = "/api/meetings/upload"
    MEETING_RECORD     = "/api/meetings/record"
    MEETING_TRANSCRIPT = "/api/meetings/{id}/transcript"
    MEETING_STATUS     = "/api/meetings/{id}/status"
    MEETING_SUMMARY    = "/api/meetings/{id}/summary"
    MEETING_REGENERATE = "/api/meetings/{id}/regenerate"
    MEETING_SHARE      = "/api/meetings/{id}/share"
    SHARE_ACCESS       = "/api/share/{token}"
